### ISSUE TITLE
Typo in instruction 

### ISSUE THREAD

**Issue by SteigerHSV** [Thore-Krug/Install-Flash-Chip-Mac#1]
> ./Flash.sh help will give out the help
> ./Flash.sh install-all install all the things you need to Flash your C.H.I.P
> ./Flash.sh flash Will Flash your C.H.I.P

Should be:

> ./Flasher.sh help will give out the help
> ./Flasher.sh install-all install all the things you need to Flash your C.H.I.P
> ./Flasher.sh flash Will Flash your C.H.I.P

**Comment by Thore-Krug** [comment]
I dont see a difference

**Comment by Thore-Krug** [comment]
Oh i just looked at the endings.... Nevermind i fixed it thank you
