### ISSUE TITLE
MacOS sunxi-tools installation

### ISSUE THREAD

**Issue by SteigerHSV** [Thore-Krug/Install-Flash-Chip-Mac#2]
on terminal:
Installing git via `sudo apt install git` is possible only if user have Java

but `git clone https://github.com/Thore-Krug/Install-Flash-Chip-Mac` force user to install developer tools that will work.

But macOS didnt have installed sunxie-tools by default even it flasher.sh works it cant flash becuse lack of sunxie-fel. it could be super good to add how to install and get this work in readme.

**Comment by Thore-Krug** [comment]
Ah sorry u just can download the repo unzip it, then open up the terminal and go to the location of the script. then run ``` sudo chmod +x Flasher.sh ``` then run ``` ./Flash.sh install-all ``` then ``` ./Flash.sh flash ```

**Comment by Oliver-Redeyoff** [comment]
Even after running` sudo chmod +x Flasher.sh`, then `./Flash.sh install-all`  and then `./Flash.sh flash`
I get the error

> Error: Unable to locate sunxi-fel utility.
  Install sunxi-fel with:
  the Setup script? 

Should sunxi-fel be installed some other way maybe?

**Comment by Thore-Krug** [comment]
U can install it from the sunxi repo but the setup compiles it and install it

**Comment by Oliver-Redeyoff** [comment]
By setup do you mean the install-all function?

**Comment by Thore-Krug** [comment]
Yes. Currently i try to recreate the error on my Machine.

**Comment by Thore-Krug** [comment]
Nope it works what is your output ? When u run the Script ?

**Comment by Oliver-Redeyoff** [comment]
I run the following command : 
sudo chmod +x Flasher.sh, 
then ./Flash.sh install-all 
and then ./Flash.sh flash

And I get the output :

> Error: Unable to locate sunxi-fel utility.
> Install sunxi-fel with:
> the Setup script?

**Comment by Thore-Krug** [comment]
i mean the whole output. U can save it with cmd +s and upload it here

**Comment by Oliver-Redeyoff** [comment]
Here is the file :

[Sunxi-fel issue output.txt](https://github.com/Thore-Krug/Install-Flash-Chip-Mac/files/3111571/Sunxi-fel.issue.output.txt)

**Comment by denis-ev** [comment]
@Thore-Krug @Oliver-Redeyoff same problem here.

**Comment by Thore-Krug** [comment]
@SteigerHSV @Oliver-Redeyoff @denis-ev  Please Redownload it and retry it i fixed it.

**Comment by Oliver-Redeyoff** [comment]
Yes that worked thanks a lot!

**Comment by Thore-Krug** [comment]
OK i close this issue now. If u have still trouble reopen a new one.
