### ISSUE TITLE
Another problem with install-all

### ISSUE THREAD

**Issue by mackemint** [Thore-Krug/Install-Flash-Chip-Mac#5]
Hi
I'm on High Sierra, running the ./Flash.sh install-all script I get the following issue:

install -d /usr/local/bin
+ for t in sunxi-fexc sunxi-bootinfo sunxi-fel sunxi-nand-part sunxi-pio
+ install -m0755 sunxi-fexc /usr/local/bin/sunxi-fexc
+ for t in sunxi-fexc sunxi-bootinfo sunxi-fel sunxi-nand-part sunxi-pio
+ install -m0755 sunxi-bootinfo /usr/local/bin/sunxi-bootinfo
+ for t in sunxi-fexc sunxi-bootinfo sunxi-fel sunxi-nand-part sunxi-pio
+ install -m0755 sunxi-fel /usr/local/bin/sunxi-fel
+ for t in sunxi-fexc sunxi-bootinfo sunxi-fel sunxi-nand-part sunxi-pio
+ install -m0755 sunxi-nand-part /usr/local/bin/sunxi-nand-part
+ for t in sunxi-fexc sunxi-bootinfo sunxi-fel sunxi-nand-part sunxi-pio
+ install -m0755 sunxi-pio /usr/local/bin/sunxi-pio
+ for l in bin2fex fex2bin
+ ln -nfs sunxi-fexc /usr/local/bin/bin2fex
+ for l in bin2fex fex2bin
+ ln -nfs sunxi-fexc /usr/local/bin/fex2bin
arm-none-eabi-gcc -std=c99 -Wall -Wextra -Wno-unused-result -D_POSIX_C_SOURCE=200112L -D_BSD_SOURCE -D_DEFAULT_SOURCE -Iinclude/ -static  -o sunxi-meminfo meminfo.c
make: arm-none-eabi-gcc: No such file or directory
make: *** [sunxi-meminfo] Error 1

Attempted to fix this by adding the px4 cask to Brew by
brew tap PX4/homebrew-px4
brew install gcc-arm-none-eabi-74

But the install-all fails at 
+ ln -nfs sunxi-fexc /usr/local/bin/fex2bin
arm-none-eabi-gcc -std=c99 -Wall -Wextra -Wno-unused-result -D_POSIX_C_SOURCE=200112L -D_BSD_SOURCE -D_DEFAULT_SOURCE -Iinclude/ -static  -o sunxi-meminfo meminfo.c
meminfo.c:22:10: fatal error: sys/mman.h: No such file or directory
 #include <sys/mman.h>
          ^~~~~~~~~~~~
compilation terminated.

What version of the gcc arm should be installed for this to work?

**Comment by mackemint** [comment]
Seems like the solution in the pinned issue [3](https://github.com/Thore-Krug/Install-Flash-Chip-Mac/issues/3) actually had an embedded solution, who would have thought.
The #include failure was quite disarming though, wasn't expecting flashing to work without building the libs correctly.

**Comment by mackemint** [comment]
so just to clarify for anyone else that has as little patience as me that encounters the same issues: 
1: clone the repo
2: Add the gcc-arm-none-eabi from brew listed above
3: run the installer and let it crash & burn, doesn't matter
4: download [this](https://dl.google.com/android/repository/platform-tools_r26.0.1-darwin.zip), unzip and copy the fastboot binary to /usr/local/Caskroom/android-platform-tools/x.y.z/platform-tools
5: Run the installer & profit.

Thx to u Thore, my C.H.I.P.s will once again from their project box slumber!

**Comment by flow23** [comment]
Hi, the modified fastboot binary doesn't work with macOS Catalina, I'm getting the same error.

`flow23@mac platform-tools % /usr/local/Caskroom/android-platform-tools/29.0.4/platform-tools/fastboot --version
fastboot version 9dc0875966c0-android
Installed as /usr/local/Caskroom/android-platform-tools/29.0.4/platform-tools/fastboot`

Did I miss something? Flashing is also not possible due to a segmentation fault when creating the image with mkimage -A arm ...
