### ISSUE TITLE
Fastboot: invalid option i

### ISSUE THREAD

**Issue by Karposaurus** [Thore-Krug/Install-Flash-Chip-Mac#6]
It gets to "waiting for fastboot" and then spams "fastboot: invalid option -- I" and leaving the chip plugged in for a bit the chip gets hot maybe ~60C

I'm using a MB Air 2012 (a1466) running Mojave (10.14.6)

Heres the log:
user-MacBook-Air:Install-Flash-Chip-Mac-master user$ ./Flasher.sh flash 

   #  #  #
  #########
###       ###
  # {#}   #
###  '\######
  #       #
########
   #  #  #
 Welcome to the C.H.I.P Flasher Tool 
 Please enter your wanted flavour 
 ++++++++++++++++++++++++++++++++++++++++++ 
 enter p for pocketchip Image 
 enter s for the headless Server Image 
 enter g for the Desktop Image 
 enter b for the Buildroot Image 
 ++++++++++++++++++++++++++++++++++++++++++ 
 IMPORTANT INFO 
 If u suffer from Power Problems add a n 
 to your choice of flavour 
 Example: gn for the No-Limit Desktop Image 
 ++++++++++++++++++++++++++++++++++++++++++ 
 Other options 
 ++++++++++++++++++++++++++++++++++++++++++ 
 enter f for Force Clean 
 ++++++++++++++++++++++++++++++++++++++++++ 
 Then press enter please 
p
Already up to date.
== Pocketchip selected ==
== preparing images ==
== Local/cached probe files located ==
== Staging for NAND probe ==
Image Name:   detect NAND
Created:      Mon Aug 12 18:26:48 2019
Image Type:   ARM Linux Script (uncompressed)
Data Size:    97 Bytes = 0.09 KiB = 0.00 MiB
Load Address: 00000000
Entry Point:  00000000
Contents:
   Image 0: 89 Bytes = 0.09 KiB = 0.00 MiB
waiting for fel...OK
waiting for fel......OK
NAND detected:
nand_erasesize=400000
nand_oobsize=680
nand_writesize=4000
== Cached UBI located ==
Image Name:   flash pocketchip
Created:      Mon Aug 12 18:26:56 2019
Image Type:   ARM Linux Script (uncompressed)
Data Size:    2189 Bytes = 2.14 KiB = 0.00 MiB
Load Address: 00000000
Entry Point:  00000000
Contents:
   Image 0: 2181 Bytes = 2.13 KiB = 0.00 MiB
waiting for fel...OK
waiting for fastboot...fastboot: invalid option -- i
.fastboot: invalid option -- i
.fastboot: invalid option -- i
.fastboot: invalid option -- i
.fastboot: invalid option -- i
.fastboot: invalid option -- i
.fastboot: invalid option -- i
.fastboot: invalid option -- i
.fastboot: invalid option -- i
.fastboot: invalid option -- i
.fastboot: invalid option -- i
.fastboot: invalid option -- i
.fastboot: invalid option -- i
.fastboot: invalid option -- i
.fastboot: invalid option -- i
.fastboot: invalid option -- i
.fastboot: invalid option -- i
.fastboot: invalid option -- i
.fastboot: invalid option -- i
.fastboot: invalid option -- i
.fastboot: invalid option -- i
.fastboot: invalid option -- i
.fastboot: invalid option -- i
.fastboot: invalid option -- i
.fastboot: invalid option -- i
.fastboot: invalid option -- i
.fastboot: invalid option -- i
.fastboot: invalid option -- i
.fastboot: invalid option -- i
.fastboot: invalid option -- i
.TIMEOUT
failed to flash the UBI image

 FLASH VERIFICATION FAILED.

	TROUBLESHOOTING:

	Is the FEL pin connected to GND?
	Have you tried turning it off and turning it on again?
	Did you run the setup script?
	Download could be corrupt, it can be re-downloaded by adding the '-f' flag.

**Comment by codycodes** [comment]
Seems to be a dependency issue with Fastboot. I'm on platform-tools version 29.0.1 and got the same error. You can follow instructions below to solve the issue. I would also recommend just renaming your existing `platform-tools` folder to `platform-tools.bak` and then after finishing delete the `platform-tools` folder and rename `platform-tools.bak` to `platform-tools` so you can use the more recent version again.

https://github.com/Thore-Krug/Install-Flash-Chip-Mac/issues/5#issuecomment-501552414

**Comment by ktong-delivery-com** [comment]
I removed both -i and -u switch and it continued without issues.
