### ISSUE TITLE
Problems installing sunxi on macOs

### ISSUE THREAD

**Issue by Dezorian** [Thore-Krug/Install-Flash-Chip-Mac#8]
I get an error when running ./Flasher.sh -install-all

Had some trouble with the arm-none-eabi-gcc compiler but i could resolve that by installing that with homebrew lib6dev (?)

now i get the following error while the Flasher scripts tries to install sunxi tools:

```
arm-none-eabi-gcc -std=c99 -Wall -Wextra -Wno-unused-result -D_POSIX_C_SOURCE=200112L -D_BSD_SOURCE -D_DEFAULT_SOURCE -Iinclude/ -static  -o sunxi-meminfo meminfo.c
meminfo.c:22:10: fatal error: sys/mman.h: No such file or directory
 #include <sys/mman.h>
          ^~~~~~~~~~~~
compilation terminated.
make: *** [sunxi-meminfo] Error 1
```

Weird things is that in /usr/include/sys does have the mman.h file.

Any ideas?

**Comment by Dezorian** [comment]
This has something to do with me installing arm toolkit through homebrew. I cannot get the sunxi tools to compile on mac. I've delete the toolkit through homebrew and installed a fresh one with npm xpack. Edited the makefile to use that one but then i get wrong architecture exceptions. I have now used a raspberry pi to flash my PocketCHIP. Is there any way to get the sunxi-tools as binary so i dont have to compile them?

**Comment by Thore-Krug** [comment]
I can send it to u I guess
